SA-24 Add download Image service
speaker378/ShikiApp pull request #13
Opened 2023-01-28 19:51 UTC by KonstantinShmondrik

Добавил сервис загрузки изображений

2023-01-29 14:24 UTC, ads63 requested changes

2023-01-29 14:24 UTC, ads63 commented on ShikiApp/Core/Extensions/UIImageView/UIImageView+downloadeImage.swift
> +            diskPath: "images"
магическое число. Я бы вынес в константы

2023-01-29 14:30 UTC, KonstantinShmondrik commented on ShikiApp/Core/Extensions/UIImageView/UIImageView+downloadeImage.swift
> +            diskPath: "images"
Вот я тоже долго думал, что с ними делать, ок, вынесу оба этих значения в константы.

2023-01-29 18:23 UTC, mpopsicle235111 approved these changes

2023-01-30 11:30 UTC, speaker378 requested changes
кейс: экран с табличкой в каждой ячейке есть картинка. 
проблемы:
    1. скорее всего ячеек в таблице будет больше 5 и отобразить нам их нужно сразу. В доке к API говорится об ограничении кол-ва одновременных запросов и равно оно 5. В лучшем случае сервер просто не откроет больше соединений за раз, в худшем получим бан на какое-то время. Либо это не касается получения картинок?
    2. Запросы будут без требуемых заголовков. Либо это не касается получения картинок?
    3.  У каждой ячейки может быть больше одной задачи на получении картинки. У каждой задачи будет свое время выполнения. Как итог периодически мы будем получать картинки из более ранней задачи (если она завершиться позже). 
    4.  Мы получаем вьюшку которая сама ходит в сеть.
    5. Если правильно понимаю, то у каждой ImageView будет создаваться своя сессия. Наверно это избыточно?
    6. Не знаю точно как это работает, но не будет ли проблем при кешировании картинок когда в разных сессиях с одной конфигурацией будут идти записи в кэш?

2023-01-30 13:14 UTC, KonstantinShmondrik commented
> кейс: экран с табличкой в каждой ячейке есть картинка.
> проблемы:
> 1. скорее всего ячеек в таблице будет больше 5 и отобразить нам их нужно сразу. В доке к API говорится об ограничении кол-ва одновременных запросов и равно оно 5. В лучшем случае сервер просто не откроет больше соединений за раз, в худшем получим бан на какое-то время. Либо это не касается получения картинок? 

Это не касается картинок. Каждая картинка будет посылать свой запрос по своему URL. Ограничение по умолчанию 4, я его расширил до 5, нам это не сильно нужно, так как мы не качаем пакетами. Этот параметр показывает сколько будет задействовано потоков **одновременно** для загрузки данных. 

> 2. Запросы будут без требуемых заголовков. Либо это не касается получения картинок?

Это не касается картинок. Если тебе пришел URL для отображения картинки, значит у тебя есть к нему доступ. 

> 3. У каждой ячейки может быть больше одной задачи на получении картинки. У каждой задачи будет свое время выполнения. Как итог периодически мы будем получать картинки из более ранней задачи (если она завершиться позже).

Если это одна и та же картинка, то она загрузится не из сети, а из кэша. Загружают не ячейки, загрузка идет с каждой UIImageView. 

> 4. Мы получаем вьюшку которая сама ходит в сеть.

По другому никак, мы же хотим отобразить изображение, которое лежит по URL где-то на сервере к которому сам же сервер дал нам доступ, прислав нам этот URL. 

> 5. Если правильно понимаю, то у каждой ImageView будет создаваться своя сессия. Наверно это избыточно?

Да это так, иначе не получится. Сессия будет закрываться, как только задача будет выполнена (картинка загружена). Можно добавить принудительный task.cansel в prepareForReuse() там где ты nil для ячеек писал, если пользователь просроллил эту ячейку, а она еще не загрузила свои картинки, то останавливать этот процесс и возвращаться к ним, когда снова доскролим до этой ячейки. Но это может быть небезопасно (можем получить ошибку), и для нас избыточное не думаю, что там приходят очень тяжелые картинки большого расширения, которое будут нам тормозить отрисовку UI. Если мы с этим столкнемся, будем думать в эту сторону. 

> 6. Не знаю точно как это работает, но не будет ли проблем при кешировании картинок когда в разных сессиях с одной конфигурацией будут идти записи в кэш?

Не должно. Он же сначала проверяет, есть ли такая картинка в кеше, если есть - берет ее, если нет - загружает. Если одновременно грузят несколько процессов, то пока она не загрузится полностью, ее для использования не существует.

2023-02-01 14:52 UTC, December11 approved these changes
Мне казалось чтобы работало по принципу - сначала проверь в кеше и скачай, если там не нашлось, нужно прописывать параметр URLCachePolicy, а по умолчанию из кеша берет только если если нет интернета. 
Можешь потом рассказать как у тебя тут это работает?

2023-02-01 14:52 UTC, December11 commented on ShikiApp/Core/Extensions/UIImageView/UIImageView+downloadeImage.swift
> +
Может быть, лучше сделать кастомную imageView, которая умеет ходить в сеть, а не делать это расширением для всего типа? Так было бы проще понять что это именно часть логики данного imageView. 
Но это так, просто предложение)

2023-02-01 17:29 UTC, KonstantinShmondrik commented on ShikiApp/Core/Extensions/UIImageView/UIImageView+downloadeImage.swift
> +
у нас почти все imageView заполняются данными из интернета

2023-02-01 17:33 UTC, KonstantinShmondrik commented on ShikiApp/Core/Extensions/UIImageView/UIImageView+downloadeImage.swift
> +// myImageView.downloadedImage(from: "http:\.........")
вот не хотел я их писать )))) Но вообще можно. Так то я предполагал, что эти объясняющий коменты мы потом уберем, когда их наденем использовать, будет из кода по аналогии понятно как этим пользоваться

2023-02-01 17:35 UTC, KonstantinShmondrik commented
> Мне казалось чтобы работало по принципу - сначала проверь в кеше и скачай, если там не нашлось, нужно прописывать параметр URLCachePolicy, а по умолчанию из кеша берет только если если нет интернета.
> Можешь потом рассказать как у тебя тут это работает?

Вроде так и работает. Только с интернетом, я сомневаюсь. Мы без интернета не получим url, который надо сверить с кешом, и статус код не будет равен 200, так что guard нас выкинет

2023-02-01 18:57 UTC, December11 commented on ShikiApp/Core/Extensions/UIImageView/UIImageView+downloadeImage.swift
> +
есть еще иконки, но ладно) Большинство наверное да, все равно берут данные из интернета, окей)

2023-02-01 19:03 UTC, KonstantinShmondrik commented on ShikiApp/Core/Extensions/UIImageView/UIImageView+downloadeImage.swift
> +
Сделал отдельный класс и добавил для примера комментарии к функции, по мне так нагромождение

2023-02-01 19:19 UTC, ads63 approved these changes

2023-02-03 17:02 UTC, speaker378 approved these changes

2023-02-03 17:02 UTC, merged