SA-38 Add Filters modul
speaker378/ShikiApp pull request #24
Opened 2023-02-14 08:17 UTC by KonstantinShmondrik

Добавил экран для выбора фильтров
Добавил модель для списка фильтров по категориям (пока моковыеданные)
Добавил модель для выбранных фильтров

2023-02-14 23:32 UTC, mpopsicle235111 approved these changes

2023-02-15 07:42 UTC, ads63 commented on ShikiApp/Core/Helpers/AppColor.swift
> +    static let shadowColor = UIColor(named: "shadowColor") ?? missingColor
в Assets ShadowColor - поправить либо там, либо здесь

2023-02-15 07:44 UTC, ads63 commented on ShikiApp/Core/Extensions/UIApplication/UIApplication+Extantion.swift
> +}
в имени файла  и шапке  Extantion поменять на Extension

2023-02-15 07:55 UTC, ads63 commented on ShikiApp/App/Flows/Filters/View/FiltersView+Extantion.swift
> +        let haight: CGFloat = dataSource.count < 5 ?
может все-таки height?

2023-02-15 07:57 UTC, ads63 commented on ShikiApp/App/Flows/Filters/View/FiltersView+Extantion.swift
> +
тут и ниже лучше бы вынести параметры анимации в  локальные константы класса

2023-02-15 08:07 UTC, ads63 requested changes
Баг в названии цвета  тени - отображается  тень цветом missingColor, остальное - косметика (см комментарии)

2023-02-15 10:37 UTC, December11 commented on ShikiApp/App/Entity/Filters/FilterListModel.swift
> +struct FilterListModel {
не перестаю душнить по поводу пустых строк в начале структуры, класса, протокола)

2023-02-15 10:37 UTC, December11 commented on ShikiApp/App/Entity/Filters/FiltersModel.swift
> +                    "Сёдзё-фй",
Сёдзё-ай. Опечатка)

2023-02-15 10:37 UTC, December11 commented on ShikiApp/App/Entity/Filters/FiltersModel.swift
> +                     "Клипт"],
Тут вроде должны быть статусы, вроде Вышел, Онгоинг и т.п.

2023-02-15 10:37 UTC, December11 commented on ShikiApp/App/Entity/Filters/FiltersModel.swift
> +                   "Спешал",
тут лучше "Спешл" - чтобы было единообразно.
и ниже опечатка - должно быть "Клип"

_Эх, у Алексея есть уже подобный список в константах. Надо будет потом привести к одному виду, **сейчас можно и так оставить.**_

2023-02-15 10:37 UTC, December11 commented on ShikiApp/App/Flows/Filters/View/FiltersViewController.swift
> +        navigationController?.navigationBar.prefersLargeTitles = true
может будем это оставлять на усмотрение следующей страницы? Т.е. на каждом вью контроллере, если надо будем делать свою настройку навбара. 
Или это для какой-то другой цели?

2023-02-15 10:37 UTC, December11 commented on ShikiApp/Core/Helpers/AppImage.swift
> +        static let options = UIImage(named: "options") ?? missingImage
вообще, я ее уже добавляла в своем PR

2023-02-15 10:43 UTC, KonstantinShmondrik commented on ShikiApp/App/Entity/Filters/FiltersModel.swift
> +                   "Спешал",
Списывал из фильтров с сайта, там так и написано Спешал

2023-02-15 10:44 UTC, KonstantinShmondrik commented on ShikiApp/App/Entity/Filters/FiltersModel.swift
> +                     "Клипт"],
Странно, почему тут так встало, я изначально писал Вышел, ожидается и т.п. Поправлю

2023-02-15 10:46 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Filters/View/FiltersViewController.swift
> +        navigationController?.navigationBar.prefersLargeTitles = true
Да, согласен, это надо удалить отсюда и добавить на страницу с которой переход осуществляется. Пока сюда добавил как временный вариант, так как не хотел сильно залазить на страницу фильтрации

2023-02-15 10:47 UTC, KonstantinShmondrik commented on ShikiApp/Core/Extensions/UIApplication/UIApplication+Extantion.swift
> +}
ок, поменяю

2023-02-15 10:47 UTC, KonstantinShmondrik commented on ShikiApp/App/Entity/Filters/FilterListModel.swift
> +struct FilterListModel {
что и в моделях тоже? )))

2023-02-15 10:49 UTC, KonstantinShmondrik commented on ShikiApp/Core/Helpers/AppImage.swift
> +        static let options = UIImage(named: "options") ?? missingImage
могу удалить у себя, мне она нужна была просто для перехода

2023-02-15 10:51 UTC, KonstantinShmondrik commented on ShikiApp/Core/Helpers/AppColor.swift
> +    static let shadowColor = UIColor(named: "shadowColor") ?? missingColor
поправлю, спасибо, хотя странно, я это правил и у меня то тень нормального цвета

2023-02-15 11:04 UTC, December11 commented on ShikiApp/App/Entity/Filters/FilterListModel.swift
> +struct FilterListModel {
ну по идее везде, где мы договаривались)

2023-02-15 11:14 UTC, December11 commented on ShikiApp/App/Entity/Filters/FiltersModel.swift
> +                   "Спешал",
Вообще, кажется обычно пишут все-таки "Спешл", а не "Спешал". Ну ладно, оставь Спешал, я тогда переименую.

2023-02-15 11:17 UTC, December11 commented on ShikiApp/Core/Helpers/AppImage.swift
> +        static let options = UIImage(named: "options") ?? missingImage
да наверн. Она у меня и называется вроде так же... `AppImage.NavigationsBarIcons.options`

2023-02-15 12:30 UTC, December11 approved these changes

2023-02-15 12:30 UTC, December11 commented on ShikiApp/App/Entity/Filters/FiltersModel.swift
>                     "Клипт"],
вот тут только Клип, а не Клипт)

2023-02-15 17:50 UTC, speaker378 reviewed
в этот раз у тебя очень много очепяток, нажми в Xcode: "  cmd + ;  "

2023-02-15 17:50 UTC, speaker378 commented on ShikiApp/App/Flows/Filters/Presenter/FiltersPresenter.swift
> +        print(filrers)
print еще нужен?

2023-02-15 17:50 UTC, speaker378 commented on ShikiApp/Core/Extensions/UIApplication/UIApplication+Extensions.swift
> +    }
Для чего этот метод? Если его убрать, то вроде все работает также

2023-02-15 17:50 UTC, speaker378 commented on ShikiApp/App/Flows/Search/SearchViewController.swift
> +    }
Видимо ты удалил ссылку а сам файл оставил, Xcode его не видит, в файлах он есть

2023-02-15 17:50 UTC, speaker378 commented on ShikiApp/App/Flows/Filters/View/MenuItemsTableViewCell.swift
> +}
Тут ничего не происходит, возможно пока, но зачем переопределять методы и просто вызывать в них методы родителя?

2023-02-15 17:50 UTC, speaker378 commented on ShikiApp/App/Flows/Filters/View/FooterFilterView.swift
> +    func tapapplyButton()
tapApplyButton

2023-02-15 17:50 UTC, speaker378 commented on ShikiApp/App/Flows/Filters/View/FiltersView+Extansion.swift
> +//  FiltersView+Extantion.swift
Extension

2023-02-15 17:50 UTC, speaker378 commented on ShikiApp/App/Flows/Filters/View/FiltersView+Extansion.swift
> +        let tapgesture = UITapGestureRecognizer(target: self, action: #selector(removeTransparentView))
tapGesture

2023-02-15 17:50 UTC, speaker378 commented on ShikiApp/App/Flows/Filters/View/FiltersView.swift
> +    private let labelOfcet: CGFloat = 32
labelOffset

2023-02-15 17:50 UTC, speaker378 commented on ShikiApp/App/Flows/Filters/View/FiltersView.swift
> +    private let bottomOfcet: CGFloat = 340
Offset

2023-02-15 18:38 UTC, ads63 commented on ShikiApp/App/Flows/Filters/View/FiltersView+Extansion.swift
> +//  FiltersView+Extantion.swift
 plz Extansion -> Extension

2023-02-15 18:39 UTC, ads63 reviewed
  Сергей все написал, нечего добавить

2023-02-16 13:14 UTC, KonstantinShmondrik commented on ShikiApp/App/Entity/Filters/FiltersModel.swift
>                     "Клипт"],
поправил

2023-02-16 13:15 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Filters/Presenter/FiltersPresenter.swift
> +        print(filrers)
пока нужен, это точка входа для экрана поиска

2023-02-16 13:19 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Filters/View/FiltersView.swift
> +    private let labelOfcet: CGFloat = 32
поправил

2023-02-16 13:19 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Filters/View/FiltersView.swift
> +    private let bottomOfcet: CGFloat = 340
поправил

2023-02-16 13:21 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Filters/View/FiltersViewController.swift
> +    private let viewOutput: FilterslViewOutput
поправил

2023-02-16 13:22 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Filters/View/FiltersViewController.swift
> +
поправил

2023-02-16 13:30 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Filters/View/FiltersViewController.swift
> +    func tapapplyButton() {
поправил

2023-02-16 13:31 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Filters/View/FiltersViewController.swift
> +        viewOutput.getFilterList(filrers: filters)
поправил

2023-02-16 13:31 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Filters/View/FooterFilterView.swift
> +    func tapapplyButton()
поправил

2023-02-16 14:05 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Filters/View/MenuItemsTableViewCell.swift
> +}
Это был задел на будущее, мы же хотели сделать там галочки. Добавил пока изменение цвета текста. Позже попробую реализовать простановку галок.

2023-02-16 14:07 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Search/SearchViewController.swift
> +    }
да, ты прав. Сейчас удалил файл целиком.

2023-02-16 14:11 UTC, KonstantinShmondrik commented on ShikiApp/Core/Extensions/UIApplication/UIApplication+Extensions.swift
> +    }
это необходимо для установки фреймов для фонового вью, которое появляется, когда выпадают списки
func addTransparentView(frames: CGRect) {
        **let window = UIApplication.firstKeyWindowForConnectedScenes**
        transparentView.frame = window?.frame ?? self.frame
        self.addSubview(transparentView)

2023-02-16 14:20 UTC, KonstantinShmondrik commented on ShikiApp/Core/Extensions/UIView/UIView+roundCorners.swift
> +        if #available(iOS 11.0, *) {
убрал лишнее

2023-02-16 14:21 UTC, KonstantinShmondrik commented on ShikiApp/Core/Extensions/UIView/UIView+roundCorners.swift
> +                cornerRadii: CGSize(width: radius, height: radius)
да

2023-02-16 14:24 UTC, KonstantinShmondrik commented on ShikiApp/Resources/Texts.swift
> +        static let raiting = "Оценка от"
поправил

2023-02-16 14:25 UTC, KonstantinShmondrik commented on ShikiApp/Resources/Texts.swift
> +        static let raiting = "Выберите оценку"
поправил

2023-02-16 14:25 UTC, KonstantinShmondrik commented on ShikiApp/Resources/Texts.swift
> +        }
поправил

2023-02-16 14:28 UTC, KonstantinShmondrik commented
> в этот раз у тебя очень много очепяток, нажми в Xcode: " cmd + ; "

спасибо, еще одно сочетание клавиш в копилку. Мне его очень не хватало

2023-02-16 15:45 UTC, ads63 approved these changes

2023-02-16 21:16 UTC, speaker378 approved these changes

2023-02-16 21:16 UTC, merged