Feature/SA-47 Add pagination to search screen
speaker378/ShikiApp pull request #26
Opened 2023-02-15 19:57 UTC by ads63

На экране поиска:
добавил загрузку страниц при скроллинге таблицы результатов
поменял иконку на кнопке Фильтры
пофиксил баг: не отрабатывал клик на ячейке таблицы для вызова экрана детальной информации. (мешал gesture recognizer)

2023-02-16 00:02 UTC, mpopsicle235111 approved these changes

2023-02-16 07:55 UTC, speaker378 requested changes

2023-02-16 07:55 UTC, speaker378 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/Presenter/SearchPresenter.swift
> +            self?.entityList.removeAll()
это дает нам небольшой баг: попробуй написать в строку поиска - океан. Придет 22 объекта, при скролле вниз пойдет 2 запрос в котором список объектов будет пуст. в результате мы получим пустую таблицу даже недосмотрев предыдущие результаты

2023-02-16 07:55 UTC, speaker378 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/View/SearchView.swift
> +//        tableView.allowsSelection = true
закоменченое дефолтное значение которое нигде не изменяется

2023-02-16 08:00 UTC, speaker378 commented
еще я бы установил textField.autocorrectionType = .no для строки поиска, словарь не знает имена аниме и постоянно исправляет

2023-02-16 08:18 UTC, speaker378 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/View/SearchViewController.swift
> +        presenter.fetchData()
мерцание при повторно переключении на экран

2023-02-16 08:38 UTC, ads63 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/View/SearchView.swift
> +//        tableView.allowsSelection = true
убрал атавизм

2023-02-16 09:39 UTC, ads63 commented
> еще я бы установил textField.autocorrectionType = .no для строки поиска, словарь не знает имена аниме и постоянно исправляет

сделал

2023-02-16 09:44 UTC, ads63 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/Presenter/SearchPresenter.swift
> +            self?.entityList.removeAll()
пофиксил, надеюсь не накосячил, но не здесь, а в refreshView()
+ поменял формирование заголовка buildHeader()

2023-02-16 09:45 UTC, speaker378 approved these changes

2023-02-17 14:43 UTC, December11 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/Presenter/SearchPresenter.swift
> +        if isLoading { return }
тут наверн лучше на `guard` заменить?

2023-02-17 14:43 UTC, December11 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/View/SearchTableCell.swift
>      private let imageWidth: CGFloat = 88
Это лишнее - я добавляла в общие константы coverWidth и сoverHeight. Они как раз для этих изображений в ячейках. Они везде одинаковы. Можно, наверн, туда же вынести высоту ячейки, она везде 112.

2023-02-17 14:43 UTC, December11 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/View/SearchTableCell.swift
>      private let lineWidth: CGFloat = 1
это ведь по идее `lineHeight`, нет?

2023-02-17 14:43 UTC, December11 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/View/Controls/ControlConstants.swift
>      static let searchPlaceHolder = "Аниме, манга, ранобэ"
кстати, давай тут переименуем на "Поиск по названию", я в Фигме не переименовала на одном из слайдов(
А то странно смотрится - выше переключалка что ищем, а ниже как будто по всему поиск.

2023-02-17 15:13 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Search/SearchResultsScreen/Presenter/SearchPresenter.swift
> +        if isLoading { return }
> тут наверн лучше на `guard` заменить?

а зачем?

2023-02-17 15:14 UTC, ads63 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/View/SearchTableCell.swift
>      private let lineWidth: CGFloat = 1
поменял, хотя толщина линии это width

2023-02-17 15:15 UTC, ads63 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/View/SearchTableCell.swift
>      private let imageWidth: CGFloat = 88
заменил

2023-02-17 15:23 UTC, ads63 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/Presenter/SearchPresenter.swift
> +        if isLoading { return }
c guard буковок получается больше, но если это принципиально, поменяю
напиши, плз, насколько это критично

2023-02-17 15:24 UTC, ads63 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/View/Controls/ControlConstants.swift
>      static let searchPlaceHolder = "Аниме, манга, ранобэ"
поменял

2023-02-17 15:30 UTC, December11 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/Presenter/SearchPresenter.swift
> +        if isLoading { return }
да не, совсем не критично, можно так оставить) Просто мне кажется, так было бы читабельнее. if c блоком `{ return }` выглядит немного странно)

2023-02-17 15:34 UTC, December11 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/View/SearchTableCell.swift
>      private let lineWidth: CGFloat = 1
у меня наверн просто профдеформация, но мне сложно думать тут о толщине линии или о ее длине) 
Ширина и высота, все как в фигме) или как в `.size()`
Спасибо)

2023-02-17 15:38 UTC, December11 approved these changes

2023-02-18 09:33 UTC, KonstantinShmondrik approved these changes

2023-02-18 11:28 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Search/SearchResultsScreen/Presenter/SearchPresenter.swift
> +        if isLoading { return }
если весь код ниже завернуть в  **if !isLoading {...}** то эта строчка вроде как и не нужна будет. 
Но это так, косметика.

2023-02-18 12:44 UTC, ads63 commented on ShikiApp/App/Flows/Search/SearchResultsScreen/Presenter/SearchPresenter.swift
> +        if isLoading { return }
Не знаю, мне кажется if с большим телом - зло. Тут сразу отсек return одну ветку "идет загрузка", и дальше пишешь код уверенный, что не идет

2023-02-18 12:46 UTC, merged