fix according to comments
speaker378/ShikiApp pull request #27
Opened 2023-02-15 23:58 UTC by mpopsicle235111

2023-02-17 08:09 UTC, ads63 requested changes

2023-02-17 08:09 UTC, ads63 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: bottom
по фигме снизу 48, а не 60

2023-02-17 08:09 UTC, ads63 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: topInset
по фигме между ними 8, а не 12

2023-02-17 08:09 UTC, ads63 commented on ShikiApp/App/Flows/Profile/Presenter/ProfilePresenter.swift
> +//  Created as per https://www.youtube.com/watch?v=2z5uWBRGjFI
ссылка на ютюб - лишнее

2023-02-17 08:09 UTC, ads63 commented on ShikiApp/App/Flows/Profile/Builder/ProfileBuilder.swift
> +//  Created as per https://www.youtube.com/watch?v=2z5uWBRGjFI
лишнее имхо ссылаться на ютюб

2023-02-17 12:32 UTC, ads63 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    var model: UserProfileDTO?
здесь уже подготовленные для отображения данные должны лежать, а не сырые из сетевого слоя
Presenter должен их сконвертировать

2023-02-17 14:24 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        imageView.clipsToBounds = true
а тут нельзя обойтись только `clipsToBounds` или `masksToBounds`?)

2023-02-17 14:24 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.font = AppFont.openSansFont(ofSize: 26, weight: .semiBold)
Я добавляла стили шрифтов в `AppFont.Styles`, лучше используй один из них. Тут точно не должно быть такого размера.

2023-02-17 14:24 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            linkImageView.heightAnchor.constraint(
нет особых причин разносить это на кучу строк, поместится и в одну. При указании констреинтов то что умещается в 120 символов лучше оставить на одной строке.

2023-02-17 14:24 UTC, December11 commented on ShikiApp/App/Flows/Profile/Presenter/ProfilePresenter.swift
> +    var model: UserProfileDTO? { get set }
тут должна быть не DTO модель, а уже подготовленная к отображению

2023-02-17 14:24 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private let labelWidthMultiplier = 0.5
зачем этот множитель? 

Проверь отступы в фигме, у тебя они не такие, как должны быть.
тоже самое касается ширины изображения - иконка там 16х16

2023-02-17 14:24 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        setupViews()
кажется, нет причин добавлять сабвьюшки в методе `loadView`. Можно добавить их в той же `configureUI()`

2023-02-17 14:24 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private let lineWidth: CGFloat = 1
кажется, это не `lineWidth`, a `lineHeight`. Название вводит в заблуждение, лучше переименуй.

2023-02-17 14:24 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: lineWidth
по фигме отступов слева и справа не должно быть. Лучше убрать тут и ниже константу. 
И полагаю, будет работать и просто `topDivider.leadingAnchor.constraint(equalTo: view.leadingAnchor)`, по идее, `safeAreaLayoutGuide` тут необязателен.

2023-02-17 23:31 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private let profileImageView: UIImageView = {
Строку убрал, спасибо.

2023-02-17 23:42 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        NSLayoutConstraint.activate([
Спасибо за совет, я тоже видел это замечание Lint, но не знал, не будет ли хуже добавить условную функцию. Сейчас исправил так: первые 43 строки (до sexAndAgeLabel) включил в первую функцию, а остальные 51 строку включил во вторую. На 51 строку Lint у меня не ругается, видимо из-за того, что пустые строки не учитываются.

2023-02-17 23:44 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        imageView.tintColor = UIColor.systemGray3
Спасибо, я просто убрал эту строку с серым цветом, ничего не поменялось, значит, действительно она была не нужна.

2023-02-17 23:47 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.nameLabelText
Я пока плохо понимаю, что конкретно тут надо сделать. Новости у нас вроде бы к пользователю не привязаны, оттуда не получится списать по образцу. "Настройка вьюхи" это то что в файле ProfileBuilder?

2023-02-18 00:02 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.font = AppFont.openSansFont(ofSize: 26, weight: .semiBold)
Спасибо, я теперь нашел, где это в Фигме указывается, и исправил на 20. В дальнейшем буду знать. 
December 11, можешь, пожалуйста, подсказать, какой будет синтаксис использования Appfont.styles?
Я сейчас еще раз перепроверил - в контроллерах Новости и Поиск вроде бы это не используется. Или я не туда куда-то смотрю?

2023-02-18 00:03 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.textColor = AppColor.textMain
Спасибо, теперь вижу, где это в Фигме прописано, сейчас проверю также и все остальные размеры.

2023-02-18 00:07 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.sexAndAgeLabelText
Пока что я не понимаю, как это исправить, мне нужно сначала понять, где происходит эта "настройка вьюхи".
Я завтра постараюсь это посмотреть где-нибудь. У нас в приложении же пока такого нет, Новости и поиск так не настраиваются?

2023-02-18 00:16 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        dividerView.layer.borderColor = UIColor.systemGray5.cgColor
Да, спасибо, в новой версии я теперь вижу. Однако в этом месте это почему-то так не работает:
dividerView.layer.borderColor = AppColor.line
дает ошибку "Cannot assign value of type 'UIColor' to type 'CGColor?'"
Посоветуй, пожалуйста, это мне надо как-то исправлять, или может быть это нужно что-то в AppColor "учесть"? Пока не справил, оставил, что было.

2023-02-18 00:18 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        button.titleLabel?.font = AppFont.openSansFont(ofSize: 20, weight: .regular)
Спасибо, я исправил на 16, буду теперь внимательно смотреть этот момент в Фирме, а не делать "на глаз".

2023-02-18 00:23 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        button.tintColor = .red
Большое спасибо, вот здесь как раз у меня все сработало, и ошибки нет. 
button.tintColor = AppColor.red - работает
dividerView.layer.borderColor = AppColor.line - выдает ошибку "Cannot assign value of type 'UIColor' to type 'CGColor?'"
Вроде бы же одинаково должно работать? Думаю. Здесь исправил, а цвет линии пока нет.

2023-02-18 00:23 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        button.titleLabel?.font = AppFont.openSansFont(ofSize: 20, weight: .regular)
Спасибо, я еще раз перепроверил - теперь у меня тут 16.

2023-02-18 00:24 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.font = AppFont.openSansFont(ofSize: 14, weight: .regular)
Виноват, исправляюсь. Теперь 12 пунктов сделал и буду впредь в Фигме смотреть и сразу делать верно.

2023-02-18 00:26 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.versionLabelText
Спасибо за замечание, я все постараюсь сделать, я просто исходил из того, что мне нужно просто разместить пока элементы на экране, о наполнении их реальными данными я еще не думал.

2023-02-18 00:31 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +//  Layouts per Akulov Ivan, https://youtu.be/T92q6dHyE0E
Акулова Ивана я убрал не глядя, это скорее для меня ссылка была, на память. 

А можно мне либо Костю оставить, либо себя не писать? Дело в том, что по разговору на последнем уроке я понял, что из незамысловатой смотрелки новостей наш проект превращается в раздатчик пиратского видео, лучше в таком деле свои персональные данные указывать поменьше...

2023-02-18 00:37 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: topInset
Спасибо, я исправил. А не подскажешь, где это мне на будущее смотреть в Фигме? Я сейчас сидел тыкал и что-то не пойму, как это определить. Я еще завтра попробую сам поискать.

2023-02-18 00:43 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            nameLabel.widthAnchor.constraint(
Пожалуйста, прошу уточнить. Мне нужно само поле прижать по правому краю на 16, но сделать выравнивание по левому краю, чтобы тест там прижимался влево, верно?

2023-02-18 00:43 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                equalTo: view.safeAreaLayoutGuide.widthAnchor,
Пожалуйста, прошу уточнить. Мне нужно само поле прижать по правому краю на 16, но сделать выравнивание по левому краю, чтобы тест там прижимался влево, верно?

2023-02-18 00:59 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: topInset+topInset
Спасибо, 16 я как раз в Фиггме нашел, надо было мышью навести на картинку Аватара, и там вышел размер. Также исправил и linkButton.

2023-02-18 01:02 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: bottom
Спасибо, я просто не вижу, где это в Фигме. Я исправил!

2023-02-18 01:05 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: topInset
Спасибо, я, к сожалению, не вижу этого размера сам в Фирме, я сделал 8.

2023-02-18 01:06 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/Presenter/ProfilePresenter.swift
> +//  Created as per https://www.youtube.com/watch?v=2z5uWBRGjFI
Понятно, я здесь ссылку убрал и больше не буду оставлять ссылки.

2023-02-18 01:07 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/Builder/ProfileBuilder.swift
> +//  Created as per https://www.youtube.com/watch?v=2z5uWBRGjFI
Понятно, я больше не буду оставлять ссылки.

2023-02-18 01:12 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    var model: UserProfileDTO?
Ясно, я попытаюсь все это как-то осмыслить. Пока я вижу, что это в новостях и поиске по-разному сделано, в новостях это некий массив, в а поиске - инициализатор. А что лучше выбрать, какой образец?

2023-02-18 01:15 UTC, mpopsicle235111 commented on ShikiApp/App/Entity/User/UserModelAPI.swift
> +struct UserModelAPI {
Прошу прощения, в новостях это есть, но я невнимательно посмотрел. Я исправил, добавил пустую строку.

2023-02-18 01:16 UTC, mpopsicle235111 commented on ShikiApp/App/Entity/User/UserModelAPI.swift
> +    let inFriends: Bool?
Спасибо, исправил здесь и ниже тоже.

2023-02-18 01:19 UTC, mpopsicle235111 commented on ShikiApp/App/Entity/User/UserModelAPI.swift
> +    let avatar: String?
К сожалению, пока не получилось здесь исправить. Выходит ошибка "Cannot find type 'avatarURLString' in scope". Этот тип данных, получается, надо где-то прописывать в расширении?

2023-02-18 08:43 UTC, ads63 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.nameLabelText
распределение обязанностей примерно такое:
1 ViewController  перед отображением запрашивает у Presenter данные для отображения
1.2 Presenter вызывает AuthManager чтобы проверить залогинен ли пользователь. Если залогинен, получает  из сетевого запроса UserProfileDTO, сразу конвертирует его в структуру, готовую для отображения. Назовем ее к примеру UserViewModel. Если не залогинен, формирует "пустую" UserViewModel. Для конвертирования UserProfileDTO в UserViewModel использует класс-фабрику, как это сделано на других экранах. Передает UserViewModel в ViewController. У тебя фабрика и модель данных для отображения  пока не реализованы.
1.3  ViewController, получив новые данные в виде UserViewModel, обновляет значения в контролах.
2. При нажатии кнопки Выйти из аккаунта: ViewController обращается к Presenter: вызывает его метод, обслуживающий выход пользователя.
2.1 Presenter  вызывает метод из AuthManager чтобы тот выполнил logOut
2.2 Presenter формирует новые данные (UserViewModel), соответствующие отсутствию залогиненного пользователя и передает их во ViewController
2.3 ViewController, получив новые данные, раскладывает их по контролам вьюхи и при необходимости рефрешит экран. В профиле вроде бы необходимости специально рефрешить нет.

2023-02-18 08:49 UTC, ads63 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    var model: UserProfileDTO?
написал выше коммент с алгоритмом работы по MVP. Должен быть некий класс, конвертирующий UserProfileDTO в модель данных, готовую для отображения.  ProfileViewController не должен ничего знать о UserProfileDTO, он получает уже готовые для отображения данные, сконвертированные из UserProfileDTO,  и раскладывает их по контролам

2023-02-18 08:54 UTC, ads63 commented on ShikiApp/App/Entity/User/UserModelAPI.swift
> +    let avatar: String?
ИМХО просто заменить avatar на avatarURLString чтоб везде, где это свойство используется, было понятно, что это не UIImage, не URL, а строка, из которой можно попробовать сделать URL и попробовать загрузить по этому URL UIImage аватарки

2023-02-18 09:54 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.font = AppFont.openSansFont(ofSize: 26, weight: .semiBold)
я добавила не так давно просто. `AppFont.Styles.title` - мне кажется так просто удобнее, выбираешь из уже подготовленных шрифтов.

2023-02-18 09:56 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        imageView.tintColor = UIColor.systemGray3
чтобы цвет применялся надо в `assets` в свойствах самого изображения выбрать Rendering as - Template image ). А иначе цвет не будет применяться, вроде как)

2023-02-18 09:59 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        dividerView.layer.borderColor = UIColor.systemGray5.cgColor
видимо там нужно CGColor, a не UIColor. напиши `AppColor.line.cgColor`

2023-02-18 10:01 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +//  Layouts per Akulov Ivan, https://youtu.be/T92q6dHyE0E
не, у нас же просто трейлеры) они вполне официальные. На сайте вроде убирают ссылки чуть кто пожалуется, так что и у нас их не будет.

2023-02-18 10:11 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: topInset
ну вообще, выбираешь в Фигме нужный элемент, и просто проводишь мышкой, чтобы увидеть расстояние до другого элемента. Иногда элемент - составная штука, тогда просто проваливаешься двойным кликом до нужного. Наверняка где-то должно быть видео как пользоваться фигмой разработчику... 
Вот статья от Фигмы https://www.figma.com/best-practices/tips-on-developer-handoff/an-overview-of-figma-for-developers/

2023-02-18 10:15 UTC, December11 commented on ShikiApp/App/Entity/User/UserModelAPI.swift
> +    let avatar: String?
не, есть же по правой кнопке мыши меню Refactor - Rename... Так можно переименовать везде, а не только в одном месте, иначе будет ругаться, как у тебя) А то да, сходу непонятен тип.

2023-02-18 12:49 UTC, ads63 commented on ShikiApp/App/Entity/User/UserModelAPI.swift
> +    let avatar: String?
ну да, через рефактор я и имел ввиду

2023-02-18 13:02 UTC, ads63 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private let lineWidth: CGFloat = 1
> кажется, это не `lineWidth`, a `lineHeight`. Название вводит в заблуждение, лучше переименуй.

вот для моего поюзаного мозга тоже логичнее толщина линии, а не высота, но большинство проголосовало за высоту. Я тоже переименовал. Пусть будет единообразно по всему проекту.

2023-02-18 22:31 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.nameLabelText
Спасибо за такую подробную "дорожную карту"! Сейчас мелкое закончу исправлять и попробую это.

2023-02-18 22:38 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.font = AppFont.openSansFont(ofSize: 26, weight: .semiBold)
В моей версии приложения Appfont.Styles еще нет. Наверное, надо это в следующей итерации исправлять. То есть я планирую сейчас все мелочи поправить, может быть, можно будет это смерджить, а потом скачать новую версию приложения, от неё сделать новый пулл-реквест, и исправлять уже там.

2023-02-18 22:40 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        dividerView.layer.borderColor = UIColor.systemGray5.cgColor
Большое спасибо, с таким синтаксисом ошибка пропала!

2023-02-18 22:57 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: topInset
[](url)
![Case1](https://user-images.githubusercontent.com/92461390/219903052-76c8f078-3204-4316-9b44-61a00e0b737e.png)
<img width="441" alt="Case2" src="https://user-images.githubusercontent.com/92461390/219903053-bdb58eb7-00ea-47eb-b8f3-472dd4a162cb.png">

2023-02-18 23:01 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: topInset
Исправленное на 24 выглядит на экране, как надо. Статью прочитал, спасибо, было интересно. Но почему-то если я мышью навожу,  ~~ парусник~~ , то есть 24 не вижу вижу 31 с половиной...

2023-02-18 23:13 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            nameLabel.widthAnchor.constraint(
Вот так пока исправил:
nameLabel.trailingAnchor.constraint(
                equalTo: view.safeAreaLayoutGuide.trailingAnchor,
                constant: trailing
            )
![Case3](https://user-images.githubusercontent.com/92461390/219903538-b2d07e5f-587b-4eea-8b04-78d9de4a5bc1.png)

Результат при длинной строке - обрезка с троеточием. Оставить так?[](url)

2023-02-18 23:18 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                equalTo: view.safeAreaLayoutGuide.widthAnchor,
Сделал так же, как для имени - если гипотетически строка удлинится (на каком-то языке мужчина и возраст будут длинными, или решим что-то еще отображать), тоже будет троеточие.
![ Case4](https://user-images.githubusercontent.com/92461390/219903655-758366f0-eef7-436e-b59e-0e37640fd501.png)

2023-02-18 23:20 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: topInset
Восемь увидел в Фигме.

2023-02-18 23:21 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: bottom
48 увидел! Навел на ТабБар, и 48 там действительно, а не 60, как я делал!

2023-02-18 23:22 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    var model: UserProfileDTO?
Большое спасибо, буду все исправлять, следуя этой дорожной карте.

2023-02-18 23:25 UTC, mpopsicle235111 commented on ShikiApp/App/Entity/User/UserModelAPI.swift
> +    let avatar: String?
Добрый вечер. Я понял, надо было не тип переменной String справа менять, а рефакторить само название переменной.
<img width="478" alt="Case5" src="https://user-images.githubusercontent.com/92461390/219903889-bae70b3c-e63e-445d-abf0-eb822c16c105.png">

 Сделал здесь и в одном месте еще было внизу этого же файла.

2023-02-18 23:29 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private var userUrlString: String = ""
Спасибо, я обратил внимание, что это вообще лишняя строчка, если ее удалить, ничего не меняется. Видимо, остался кусок моего старого кода. Я просто эту строку удалил.
<img width="618" alt="Case6" src="https://user-images.githubusercontent.com/92461390/219904007-35e720aa-d199-49ca-80b3-933f70d0c0c4.png">

2023-02-18 23:32 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        imageView.clipsToBounds = true
Спасибо, я откуда-то списывал, и списал плохо.
Я удалил clipsToBound, masksToBounds оставил, изображение все равно скрепляется, как надо.

2023-02-18 23:37 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            linkImageView.heightAnchor.constraint(
Я понял, я все исправлю, только хочу на всякий случай уточнить: мне вот так переделать, это нормально буде
<img width="1017" alt="Case7" src="https://user-images.githubusercontent.com/92461390/219904258-c4f1f8bd-cf8d-4045-b2ea-a18aad0c373e.png">
т?

2023-02-18 23:42 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private let labelWidthMultiplier = 0.5
Спасибо, меня уже ads63 поправил, множителя больше нет. Я пока сделал, как он предложил: привязал ширину лейбла к правому краю на 16.
==========
[ads63](https://github.com/ads63) [yesterday](https://github.com/speaker378/ShikiApp/pull/27#discussion_r1109403049)
если по фигме смотреть, то не 0.5 ширины, а меньше. Я бы сделал по правому краю стандартный отступ 16 (все равно справа ничего нет) и пусть отображается сколько поместится. Можно еще кол-во строк задать в контроле на случай, если в одну не влезет
==========
Итого получилось (при длинных строках) так:

![](https://user-images.githubusercontent.com/92461390/219903655-758366f0-eef7-436e-b59e-0e37640fd501.png)

2023-02-18 23:46 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private let labelWidthMultiplier = 0.5
Скажи, пожалуйста, вот именно здесь мне 16х16 нужно сделать? Я исправлю, если нужно:
![Case 8](https://user-images.githubusercontent.com/92461390/219904534-d3eefac4-93a3-4486-b803-eab7f33a68c5.png)

2023-02-18 23:51 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        setupViews()
Спасибо,  метод loadView я удалил и записал setupViews в ConfigureUI ПЕРЕД установкой констрейтнов.
Все работает.

2023-02-18 23:56 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private let lineWidth: CGFloat = 1
Спасибо, понял, переименовал в lineHeight. Все работает.

2023-02-18 23:58 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: lineWidth
Спасибо, исправил:  отступы убрал, safeAreaLayoutGuide убрал, константу убрал. Все работает.

2023-02-19 00:12 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +                constant: topInset
ну конкретно тут, эти лейблы: имя, пол-возраст и когда был онлайн - по центру (вертикальной оси) от аватара. 
Посмотри на фрейм левее, без надписи "был 2 часа онлайн". Там расстояние 25.5, что ближе к 24, чем к 12, которые были раньше. Можно сказать что этот размер оттуда. 

Вот этот значок показывает что между элементами выравнивание как StackView. Там и иконка показывает какое выравнивание. 
<img width="600" alt="Снимок экрана 2023-02-19 в 02 04 53" src="https://user-images.githubusercontent.com/5106275/219905066-06ffd3f8-99e2-41dd-86f7-af6ea64ce936.png">

2023-02-19 00:15 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            nameLabel.widthAnchor.constraint(
да, оставь так. Я, если честно, забыла отрисовать как будет выглядеть когда имя длинное. 
Кстати, ссылка не того цвета, нужен наш `AppColor.accent`)

2023-02-19 00:17 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private var userUrlString: String = ""
JFYI, можешь не кидать скрины кода, мы его все равно увидим, когда сделаешь следующий коммит ;)

2023-02-19 00:23 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            linkImageView.heightAnchor.constraint(
только то что целиком влезает на одну строку) если не влезает на 120 символов, то оставь как в последнем констреинте. 
Я вот про такие относительно короткие говорила `linkImageView.widthAnchor.constraint(equalToConstant: linkImgWidth),` они должны нормально умещаться в одну строку.

2023-02-19 00:26 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private let labelWidthMultiplier = 0.5
да, тут. Ты выбрал не фрейм с изображением, а само изображение. Ты выбрал не фрейм(где иконка ромбика), а его внутренность, оттого такой размер.
<img width="648" alt="Снимок экрана 2023-02-19 в 02 25 14" src="https://user-images.githubusercontent.com/5106275/219905479-50d939ef-5ffe-4148-b587-ba77f50a7277.png">

2023-02-19 11:20 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.font = AppFont.openSansFont(ofSize: 26, weight: .semiBold)
Окей, тогда просто `AppFont.openSansFont(ofSize: 20, weight: .semiBold)
`

2023-02-19 18:04 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +    private let labelWidthMultiplier = 0.5
Я понял, исправил на 16, спасибо.

2023-02-19 18:07 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.font = AppFont.openSansFont(ofSize: 26, weight: .semiBold)
Понял, оставляю так.

2023-02-19 18:12 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            nameLabel.widthAnchor.constraint(
Спасибо, цвет ссылки я тоже поправил на AppColor.accent

2023-02-19 19:19 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            linkImageView.heightAnchor.constraint(
Оказывается, в Линтере стоит настройка, что если аргумент не влезает на строку, то закрывающие скобки должны быть на отдельных строках. "Multiline Arguments Brackets Violation: Multiline arguments should have their surrounding brackets in a new line. (multiline_arguments_brackets)".

Я проверил каждую строчку, везде, где не ругался линтер - я исправил. Есть интересный случай: если запятая вылезает за границу, линтер не ругается. Получается, запятую можно оставить?
<img width="276" alt="Снимок экрана 2023-02-19 в 22 15 52" src="https://user-images.githubusercontent.com/92461390/219970236-f56629eb-74a5-4c9c-80d0-f944f4f81242.png">

2023-02-19 19:23 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            linkImageView.heightAnchor.constraint(
<img width="252" alt="Снимок экрана 2023-02-19 в 22 21 05" src="https://user-images.githubusercontent.com/92461390/219970393-da2ea2fe-1a27-46e2-93a5-83cae2e98e40.png">
 Ха, и здесь не ругается. Я тогда пока везде, где не ругается, небольшие хвостики оставляю висеть?

2023-02-19 19:31 UTC, December11 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            linkImageView.heightAnchor.constraint(
Икскод внизу пишет какая ширина строки, когда переводишь курсор на строку. У тебя там наверное меньше 120

2023-02-19 19:54 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +            linkImageView.heightAnchor.constraint(
<img width="632" alt="Sample10" src="https://user-images.githubusercontent.com/92461390/219971675-41cdc48b-aa6f-406b-bd1b-de668e53bd73.png">

Я обратил внимание, что теоретически можно использовать константы размеров (16 там есть, 48 есть, 8 есть) но решил это не применять, так как контроллер маленький и все тут в нем сразу видно, а в файл с константами смотреть будет неудобно. И строчки мне кажется получаются длиннее.

2023-02-21 21:01 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.nameLabelText
Ступень 1 у меня, кажется, уже готова:  во ВьюКонтроллере во вьюдидлоаде функция presenter.fetchData() запрашивает у презентера данные:

override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
        presenter.fetchData()
    }

Теперь в презентере  внутри этой функции хочу вызвать AuthManager:

func fetchData() {
        if AuthManager().isAuth() == true {
            print("User Is Logged In")
            ApiFactory.makeUsersApi()
        } else {
            print("User is not logged in")
        }
    }

Но выходит ошибка: 'AuthManager' initializer is inaccessible due to 'private' protection level.

2023-02-21 22:20 UTC, ads63 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.nameLabelText
Если откроешь AuthManager, увидишь, что это синглтон
соответственно звать его
AuthManager.share.isAuth()

2023-02-23 13:49 UTC, ads63 approved these changes
Когда будешь подключать сетевой слой, посмотри лишние пустые строки
И не уверен, что все поля UserModelAPI понадобятся для отображения.

2023-02-24 00:29 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.nameLabelText
Большое спасибо, я так и сделал.
К сожалению, в моей версии приложения юзер не залогинен.
Буду, значит, пока делать моковую UserViewModel.

2023-02-24 19:43 UTC, December11 approved these changes

2023-02-24 22:16 UTC, mpopsicle235111 commented
> Когда будешь подключать сетевой слой, посмотри лишние пустые строки
> И не уверен, что все поля UserModelAPI понадобятся для отображения.
> Если правильно понял, эта структура для отображения.
> Если это так, то 1. суффикс API неуместен 2. в ней должны быть поля уже готовые для отображения: просто взял и подставил во view без всяких преобразований: развертывания опционалов, замены английских названий на русские и т.п.

Понял, спасибо. Делаю по NewsModel, соответственно, у меня UserModel.

2023-02-24 23:30 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.nameLabelText
Пока думаю, как решить ошибку "Class 'ProfilePresenter' has no initializers"
Делаю по аналогии с NewsModelFactory, но там массив новостей, а у меня один профайл пользователя, видимо, плохо переделываю большую модель с массивом массивов в модель с только одним массивом.

2023-02-25 16:24 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Profile/Presenter/ProfilePresenter.swift
> +                guard var data else {
почему var data? надо заменить на let data

2023-02-25 16:29 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Profile/Presenter/ProfilePresenter.swift
> +    private var userData: UserDTO
так нельзя оставлять. Класс будет требовать инициализацию. Поставь вконце ?

2023-02-25 16:30 UTC, KonstantinShmondrik commented on ShikiApp/App/Flows/Profile/Presenter/ProfilePresenter.swift
> +    func isAuth() -> Bool
этого метода нет в контроллере

2023-02-26 00:32 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/Presenter/ProfilePresenter.swift
> +    private var userData: UserDTO
БОЛЬШОЕ СПАСИБО! Я это исправил, и вчерашняя ошибка у меня ушла!

2023-02-26 00:33 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/Presenter/ProfilePresenter.swift
> +                guard var data else {
Спасибо, исправил!

2023-02-26 00:45 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/Presenter/ProfilePresenter.swift
> +    func isAuth() -> Bool
Спасибо, я добавил, работает! В том смысле, что компилируется без ошибок.

2023-02-26 00:52 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/Presenter/ProfilePresenter.swift
> +    var model: UserProfileDTO? { get set }
Спасибо, я по "дорожной карте" добрался досюда и исправил на новую UserViewModel.

2023-02-26 00:56 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.sexAndAgeLabelText
Ага, видимо, я добрался до этого места, потому что у меня при попытке присвоить во ВьюКонтроллере данные из модели выходит ошибка: "Cannot use instance member 'model' within property initializer; property initializers run before 'self' is available". Буду думать!

2023-02-26 14:35 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.nameLabelText
Ошибку решил. "Придется вытаскивать в процедуру настройки вьюхи на профиль юзера" вроде бы тоже решил - переношу присвоение значений в configureUI. Пока видимо буду маковые данные там отображать.

2023-02-26 15:56 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.text = Texts.DummyTextForProfileVC.sexAndAgeLabelText
Перенес пока все моковые данные в configureUI

2023-02-26 16:10 UTC, mpopsicle235111 commented on ShikiApp/App/Flows/Profile/View/ProfileViewController.swift
> +        label.font = AppFont.openSansFont(ofSize: 26, weight: .semiBold)
Аааа, там не AppFont.Styles.titlle, а теперь AppFont.Style.title!   Сейчас везде переправлю!

2023-02-26 17:14 UTC, KonstantinShmondrik approved these changes

2023-02-26 17:29 UTC, speaker378 approved these changes

2023-02-26 17:31 UTC, merged