Feature/sa 9
speaker378/ShikiApp pull request #7
Opened 2023-01-24 15:48 UTC by ads63

Добавил ядро сетевого слоя
 App/Core/Network/*
Добавил фабрики запросов  для  API  Forums, Topics, Users:
App/BusinessLogic/Network/Forums/*
App/BusinessLogic/Network/Topics/*
App/BusinessLogic/Network/Users/*
Добавил фабрику фабрик запросов  App/BusinessLogic/Network/ApiFactory.swift
Добавил AppSettings.xcconfig для хранения базового URL
Временное решение пока не появится аутентификация : токен и юзер агент читаются из Environment variables TOKEN, USER_AGENT

2023-01-24 20:55 UTC, December11 commented on ShikiApp/App/BusinessLogic/Network/ApiFactory.swift
> +    static func makeForumsApi() -> ForumsRequestFactory { ForumsRequestFactory(agent: agent) }
так как это статичная функция, лучше раскрыть тут блоки. 
Хоть и умещается тут все в одну строку, но будет читабельнее. 
Актуально и для того что ниже

2023-01-24 20:55 UTC, December11 commented on ShikiApp/App/BusinessLogic/Network/Forums/ForumsRequestFactory.swift
> +    func listForums(completion: @escaping (_ response: ForumsResponseDTO?, _ error: String?) -> Void) { getResponse(type: ForumsResponseDTO.self, endPoint: .list, completion: completion) }
тут тоже, блок лучше раскрыть 
```
func listForums(completion: @escaping (_ response: ForumsResponseDTO?, _ error: String?) -> Void) {   
    getResponse(type: ForumsResponseDTO.self, endPoint: .list, completion: completion)   
}
```

2023-01-24 20:55 UTC, December11 commented on ShikiApp/App/BusinessLogic/Network/Topics/DTOModels/TopicsResponseDTO.swift
> +struct Linked: Codable {
тут должно быть LinkedDTO, по аналогии со всеми остальными структурами

2023-01-24 20:55 UTC, December11 commented on ShikiApp/App/BusinessLogic/Network/Topics/TopicsRequestFactory.swift
> +    func listTopics(page: Int? = nil, limit: Int? = nil, forum: ForumParameter? = nil, linkedId: Int? = nil, linkedType: LinkedTypeParameter? = nil, type: TopicTypeParameter? = nil, completion: @esca
тут кажется не влезает в 150 символов, стоит разнести параметры по строкам.

2023-01-24 20:55 UTC, December11 commented on ShikiApp/App/BusinessLogic/Network/Topics/TopicsRequestFactory.swift
> +        getResponse(type: TopicsResponseDTO.self, endPoint: .listTopics(parameters: parameters), completion: completion)
тоже больше нашего ограничения по строке

2023-01-24 20:55 UTC, December11 commented on ShikiApp/App/BusinessLogic/Network/Topics/TopicsRequestFactory.swift
> +            if let page = page, (1 ... APIRestrictions.maxPages.rawValue).contains(page) { parameters[APIKeys.page.rawValue] = page
хоть и влезает в 150 - лучше раскрывать блоки, т.е. перенести parameters..... на другую строку

2023-01-24 20:55 UTC, December11 commented on ShikiApp/App/BusinessLogic/Network/Users/UsersRequestFactory.swift
> +                                              parameters: validateParameters(page: page, limit: limit, status: status, isCensored: isCensored)),
тут чуть поехали отступы

2023-01-24 20:55 UTC, December11 commented on ShikiApp/Core/Network/ErrorParser.swift
> +
кажется, этот файл уже не нужен)

2023-01-24 20:55 UTC, December11 commented on ShikiApp/Core/Network/Router.swift
> +    internal var token: String?
`internal` не нужен

2023-01-24 20:55 UTC, December11 commented on ShikiApp/Core/Network/Router.swift
> +    fileprivate func buildRequest(from route: EndPoint) throws -> URLRequest {
тут нужен именно `fileprivate`? может `private` тоже пойдет?

2023-01-24 20:55 UTC, December11 commented on ShikiApp/Core/Network/URLParameterEncoder.swift
> +                                             resolvingAgainstBaseURL: false), !parameters.isEmpty {
тут влезет в одну строку. в блоке `for` ниже тоже)

2023-01-25 09:30 UTC, KonstantinShmondrik commented on ShikiApp/App/BusinessLogic/Network/AbstractRequestFactory.swift
> +                if let error = error {
нет, тут логичнее использовать guard

2023-01-25 09:36 UTC, KonstantinShmondrik commented on ShikiApp/App/BusinessLogic/Network/AbstractRequestFactory.swift
> +    }
109 строк - это весь класс, функции вполне нормальные по объему

2023-01-25 09:37 UTC, KonstantinShmondrik commented on ShikiApp/App/BusinessLogic/Network/AbstractRequestFactory.swift
> +    case authenticationError = "You need to be authenticated first."
все статичные String было бы не плохо вынести в отдельный для этого Энам Texts, а тут уже вызывать данные из него

2023-01-25 13:42 UTC, mpopsicle235111 reviewed
Ага, значит я у себя должен переименовать модель UserProfile в UserProfileDTO

2023-01-25 13:46 UTC, mpopsicle235111 commented on ShikiApp/App/BusinessLogic/Network/Users/DTOModels/UserProfileDTO.swift
> +struct UserProfileDTO: Codable {
О! Значит, мне мою модель UserProfile надо переименовать в UserProfileDTO

2023-01-25 14:03 UTC, mpopsicle235111 approved these changes

2023-01-25 15:52 UTC, ads63 commented on ShikiApp/App/BusinessLogic/Network/AbstractRequestFactory.swift
> +                if let error = error {
поменял по codestyle чтоб основная ветка логики была слева, а обработка ситуаций правее

2023-01-25 15:55 UTC, ads63 commented on ShikiApp/App/BusinessLogic/Network/AbstractRequestFactory.swift
> +    internal func getResponse<RESPONSE: Codable>(type: RESPONSE.Type, endPoint: API, completion: @escaping (_ response: RESPONSE?, _ error: String?) -> Void) {
потому, что привык на джаве и одной буквой капсом параметр дженерика обозначать, а lint не дает. Прочитал code style, поменял на Response

2023-01-25 16:00 UTC, ads63 commented on ShikiApp/App/BusinessLogic/Network/AbstractRequestFactory.swift
> +    }
Тут спорный вопрос ИМХО: нужно ли nested func выносить из родителя в класс и делать private если она нужна только родителю. 
Что хуже: расширение области дочерней функции до класса (нигде в классе она не нужна) или длинный код родительской функции?
Поджался и запихнул parent func + nested в 40 строк чтоб lint не ругался

2023-01-25 16:05 UTC, ads63 commented on ShikiApp/App/BusinessLogic/Network/Topics/DTOModels/TopicsResponseDTO.swift
> +struct Linked: Codable {
 done

2023-01-25 16:12 UTC, ads63 commented on ShikiApp/Core/Network/ErrorParser.swift
> +
угу, удалил ссылку в проекте на него, но в гите он остался. теперь удалил полностью

2023-01-25 16:30 UTC, ads63 commented on ShikiApp/App/BusinessLogic/Network/AbstractRequestFactory.swift
> +    case authenticationError = "You need to be authenticated first."
вынес в NetworkLayerErrorMessages

2023-01-26 10:43 UTC, December11 approved these changes

2023-01-26 10:43 UTC, December11 commented on ShikiApp/App/BusinessLogic/Network/AbstractRequestFactory.swift
> +    }
Ну почему, приватные функции используются internal функцией, мне кажется, в этом не было бы ничего плохого, но не готова тут спорить) 
Спасибо что подрефачил, давай оставим так) 👍

2023-01-27 18:25 UTC, speaker378 requested changes
надо починить .pbxproj

2023-01-27 18:25 UTC, speaker378 commented on ShikiAppTests/TopicsApiTests.swift
> +    func testlistTopics() throws {
testListTopics

2023-01-27 18:25 UTC, speaker378 commented on ShikiAppTests/UsersApiTests.swift
> +    func testlistUsers() throws {
func testListUsers()

2023-01-27 18:25 UTC, speaker378 commented on ShikiApp/App/BusinessLogic/Network/NetworkResponse.swift
> +            return NetworkLayerErrorMessages.badRequest.rawValue
зачем так усложнять? 
NetworkLayerErrorMessages.rawValue не достаточно?

2023-01-27 18:25 UTC, speaker378 commented on ShikiApp/App/BusinessLogic/Network/ApiFactory.swift
> +    static func makeAnonimousTopicsApi() -> TopicsRequestFactoryProtocol
Anonymous

2023-01-27 18:25 UTC, speaker378 commented on ShikiApp/App/BusinessLogic/Network/AbstractRequestFactory.swift
> +        router.request(endPoint) { data, response, error in
очень большое тело

2023-01-27 18:25 UTC, speaker378 commented on ShikiApp/App/BusinessLogic/Network/Topics/TopicsRequestFactory.swift
> +        if let fieldsToChange = validatePatameters(title: title,
validateParameters

2023-01-29 12:21 UTC, speaker378 approved these changes

2023-01-29 17:06 UTC, KonstantinShmondrik approved these changes

2023-01-29 17:07 UTC, merged